// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsiqI1a_56bAstQJ5BwGi2CAduFXyrDPY',
    appId: '1:106198118755:web:2cd91808be590a73c3a356',
    messagingSenderId: '106198118755',
    projectId: 'stockman-ade94',
    authDomain: 'stockman-ade94.firebaseapp.com',
    storageBucket: 'stockman-ade94.firebasestorage.app',
    measurementId: 'G-WTZ419Z02J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt3SjVyRvZHpPUEerWr0uD6SCQiQdZqs4',
    appId: '1:106198118755:android:8a881a1eefb1b910c3a356',
    messagingSenderId: '106198118755',
    projectId: 'stockman-ade94',
    storageBucket: 'stockman-ade94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF7nUEekIPDjyC0IqWrglHbraiPyGawSc',
    appId: '1:106198118755:ios:36cab8c741531ef8c3a356',
    messagingSenderId: '106198118755',
    projectId: 'stockman-ade94',
    storageBucket: 'stockman-ade94.firebasestorage.app',
    iosBundleId: 'com.example.stockman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF7nUEekIPDjyC0IqWrglHbraiPyGawSc',
    appId: '1:106198118755:ios:36cab8c741531ef8c3a356',
    messagingSenderId: '106198118755',
    projectId: 'stockman-ade94',
    storageBucket: 'stockman-ade94.firebasestorage.app',
    iosBundleId: 'com.example.stockman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsiqI1a_56bAstQJ5BwGi2CAduFXyrDPY',
    appId: '1:106198118755:web:5dae70a068cc54f0c3a356',
    messagingSenderId: '106198118755',
    projectId: 'stockman-ade94',
    authDomain: 'stockman-ade94.firebaseapp.com',
    storageBucket: 'stockman-ade94.firebasestorage.app',
    measurementId: 'G-MYTS44JE1N',
  );

}