import 'dart:io';
import 'package:stockman/src/models/cattle_document.dart';
import 'package:stockman/src/config/constants.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class CattleDocumentDbService {
  final SupabaseClient _supabase = Supabase.instance.client;
  static const String bucketName = 'cattle-documents';

  CattleDocumentDbService() {
    dlog('CattleDocumentDbService initialized with Supabase');
  }

  /// Generate storage path using document UUID
  /// Format: farm_id/cattle_id/branding/<uuid>.pdf
  String _generateStoragePath({
    required String farmId,
    required String cattleId,
    required String documentType,
    required String documentId,
    required String fileExtension,
  }) {
    final extension =
        fileExtension.startsWith('.') ? fileExtension : '.$fileExtension';
    return '$farmId/$cattleId/$documentType/$documentId$extension';
  }

  // Fetch all documents for a specific cattle
  Future<List<CattleDocument>> getDocuments({
    required String cattleId,
  }) async {
    try {
      dlog('Fetching documents for cattleId: $cattleId');

      final response = await _supabase
          .from('cattle_documents')
          .select()
          .eq('cattle_id', cattleId)
          .order('uploaded_at', ascending: false);

      dlog('Fetched ${response.length} documents');

      return response.map<CattleDocument>((data) {
        return CattleDocument.fromJson(data);
      }).toList();
    } catch (e) {
      dlog('Error fetching cattle documents: $e');
      return [];
    }
  }

  // Get documents by type
  Future<List<CattleDocument>> getDocumentsByType({
    required String cattleId,
    required String type,
  }) async {
    try {
      dlog('Fetching $type documents for cattleId: $cattleId');

      final response = await _supabase
          .from('cattle_documents')
          .select()
          .eq('cattle_id', cattleId)
          .eq('type', type)
          .order('uploaded_at', ascending: false);

      dlog('Fetched ${response.length} $type documents');

      return response.map<CattleDocument>((data) {
        return CattleDocument.fromJson(data);
      }).toList();
    } catch (e) {
      dlog('Error fetching cattle documents by type: $e');
      return [];
    }
  }

  // Get a single document by ID
  Future<CattleDocument?> getDocumentById(String documentId) async {
    try {
      final response = await _supabase
          .from('cattle_documents')
          .select()
          .eq('id', documentId)
          .maybeSingle();

      if (response == null) {
        dlog('No document found with ID: $documentId');
        return null;
      }

      return CattleDocument.fromJson(response);
    } catch (e) {
      dlog('Error fetching document by ID: $e');
      return null;
    }
  }

  /// Upload a document file to Supabase Storage and create database record
  /// This is the primary method to add documents - handles both storage and database
  Future<CattleDocument> uploadDocument({
    required String farmId,
    required String cattleId,
    required File file,
    required String documentType, // 'branding'
    String? title,
  }) async {
    String? documentId;
    try {
      // Get file extension
      final fileExtension = file.path.split('.').last;

      // Step 1: Create database entry first to get the UUID
      final tempDocument = CattleDocument(
        id: '', // Will be generated by database
        cattleId: cattleId,
        type: documentType,
        filePath: '', // Will be updated after upload
        title: title,
        uploadedAt: DateTime.now(),
      );

      final data = tempDocument.toJson();
      final response = await _supabase
          .from('cattle_documents')
          .insert(data)
          .select()
          .single();

      documentId = response['id'] as String;
      dlog('Document record created with ID: $documentId');

      // Step 2: Generate storage path using the document UUID
      final storagePath = _generateStoragePath(
        farmId: farmId,
        cattleId: cattleId,
        documentType: documentType,
        documentId: documentId,
        fileExtension: fileExtension,
      );

      // Step 3: Upload file to Supabase Storage
      try {
        await _supabase.storage.from(bucketName).upload(storagePath, file);
        dlog('Document uploaded to storage: $storagePath');
      } catch (storageError) {
        // If storage upload fails, delete the database record to avoid orphaned entries
        dlog('Storage upload failed, cleaning up database record: $documentId');
        await _supabase.from('cattle_documents').delete().eq('id', documentId);

        // Rethrow with helpful message
        throw Exception(
            'Storage upload failed. Please ensure the storage bucket "$bucketName" exists and has proper RLS policies. Original error: $storageError');
      }

      // Step 4: Update database record with the file path
      await _supabase
          .from('cattle_documents')
          .update({'file_path': storagePath}).eq('id', documentId);

      dlog('Document file_path updated in database');

      // Return the complete document
      return CattleDocument(
        id: documentId,
        cattleId: cattleId,
        type: documentType,
        filePath: storagePath,
        title: title,
        uploadedAt: tempDocument.uploadedAt,
      );
    } catch (e) {
      dlog('Error uploading document: $e');
      rethrow;
    }
  }

  /// Upload multiple documents at once
  Future<List<CattleDocument>> uploadMultipleDocuments({
    required String farmId,
    required String cattleId,
    required List<File> files,
    required String documentType,
    String? titlePrefix,
  }) async {
    final List<CattleDocument> uploadedDocuments = [];

    for (int i = 0; i < files.length; i++) {
      try {
        final title =
            titlePrefix != null ? '$titlePrefix ${i + 1}' : 'Document ${i + 1}';

        final document = await uploadDocument(
          farmId: farmId,
          cattleId: cattleId,
          file: files[i],
          documentType: documentType,
          title: title,
        );

        uploadedDocuments.add(document);
      } catch (e) {
        dlog('Error uploading document ${i + 1}: $e');
        // Continue uploading other files even if one fails
      }
    }

    return uploadedDocuments;
  }

  // Update a document (e.g., update title)
  Future<void> updateDocument({
    required String documentId,
    required CattleDocument document,
  }) async {
    try {
      final data = document.toJson();

      await _supabase
          .from('cattle_documents')
          .update(data)
          .eq('id', documentId);

      dlog('Document updated successfully');
    } catch (e) {
      dlog('Error updating document: $e');
      rethrow;
    }
  }

  // Update document title
  Future<void> updateDocumentTitle({
    required String documentId,
    required String title,
  }) async {
    try {
      await _supabase
          .from('cattle_documents')
          .update({'title': title}).eq('id', documentId);

      dlog('Document title updated successfully');
    } catch (e) {
      dlog('Error updating document title: $e');
      rethrow;
    }
  }

  // Delete a document from storage and database
  Future<void> deleteDocument({
    required String documentId,
  }) async {
    try {
      // Get document to retrieve file path
      final doc = await getDocumentById(documentId);

      if (doc != null && doc.filePath.isNotEmpty) {
        // Delete from storage
        await _supabase.storage.from(bucketName).remove([doc.filePath]);
        dlog('Document deleted from storage: ${doc.filePath}');
      }

      // Delete from database
      await _supabase.from('cattle_documents').delete().eq('id', documentId);

      dlog('Document record deleted from database');
    } catch (e) {
      dlog('Error deleting document: $e');
      rethrow;
    }
  }

  /// Delete multiple documents
  Future<void> deleteMultipleDocuments({
    required List<String> documentIds,
  }) async {
    for (final id in documentIds) {
      try {
        await deleteDocument(documentId: id);
      } catch (e) {
        dlog('Error deleting document $id: $e');
        // Continue deleting other documents
      }
    }
  }

  /// Delete all documents for a specific cattle
  Future<void> deleteAllCattleDocuments({
    required String cattleId,
  }) async {
    try {
      final documents = await getDocuments(cattleId: cattleId);

      if (documents.isEmpty) {
        dlog('No documents found for cattle: $cattleId');
        return;
      }

      final documentIds = documents.map((doc) => doc.id).toList();
      await deleteMultipleDocuments(documentIds: documentIds);

      dlog('All documents deleted for cattle: $cattleId');
    } catch (e) {
      dlog('Error deleting all cattle documents: $e');
      rethrow;
    }
  }

  /// Get public URL for a document
  String getDocumentUrl(String filePath) {
    try {
      return _supabase.storage.from(bucketName).getPublicUrl(filePath);
    } catch (e) {
      dlog('Error getting document URL: $e');
      rethrow;
    }
  }

  /// Download a document file
  Future<List<int>> downloadDocument(String filePath) async {
    try {
      dlog('Downloading document from: $filePath');
      final file = await _supabase.storage.from(bucketName).download(filePath);
      dlog('Document downloaded successfully');
      return file;
    } catch (e) {
      dlog('Error downloading document: $e');
      rethrow;
    }
  }

  // Get branding documents specifically
  Future<List<CattleDocument>> getBrandingDocuments({
    required String cattleId,
  }) async {
    return getDocumentsByType(cattleId: cattleId, type: 'branding');
  }
}
